GET http://localhost:5000/products

###
// get by id
GET http://localhost:5000/products/1

###
// create product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 3",
    "price": 456
}

###
/// Update
PATCH  http://localhost:5000/products/3
Content-Type: application/json

{
    "name": "Product 3 Update",
    "price": 989
}

###
// delete
DELETE http://localhost:5000/products/3